// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDg1XP2T6kIhkMY7ZRgN02yT9cNML3CBAI',
    appId: '1:531841284748:web:3b4d256e51387a491619a9',
    messagingSenderId: '531841284748',
    projectId: 'quote-16417',
    authDomain: 'quote-16417.firebaseapp.com',
    storageBucket: 'quote-16417.firebasestorage.app',
    measurementId: 'G-2D1VB5WEFS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9Rhsb21ctcUj0QsoIRvIlQV1GN9tlESE',
    appId: '1:531841284748:android:b5ef98987f5c41aa1619a9',
    messagingSenderId: '531841284748',
    projectId: 'quote-16417',
    storageBucket: 'quote-16417.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBE88w4yD1hAO9MJ5qsYV8AGTgAYXg5zJ0',
    appId: '1:531841284748:ios:7e58dec1f7ffdf9b1619a9',
    messagingSenderId: '531841284748',
    projectId: 'quote-16417',
    storageBucket: 'quote-16417.firebasestorage.app',
    iosBundleId: 'com.example.quote',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBE88w4yD1hAO9MJ5qsYV8AGTgAYXg5zJ0',
    appId: '1:531841284748:ios:7e58dec1f7ffdf9b1619a9',
    messagingSenderId: '531841284748',
    projectId: 'quote-16417',
    storageBucket: 'quote-16417.firebasestorage.app',
    iosBundleId: 'com.example.quote',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDg1XP2T6kIhkMY7ZRgN02yT9cNML3CBAI',
    appId: '1:531841284748:web:f9e67573498097bf1619a9',
    messagingSenderId: '531841284748',
    projectId: 'quote-16417',
    authDomain: 'quote-16417.firebaseapp.com',
    storageBucket: 'quote-16417.firebasestorage.app',
    measurementId: 'G-TTB0SBLY0H',
  );
}
